# Generated by Django 4.1.7 on 2023-04-01 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=30)),
                ('narx', models.SmallIntegerField()),
                ('berilgan_sana', models.DateField()),
                ('miqdori', models.SmallIntegerField()),
                ('olchov', models.TextField()),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('dokon_nomi', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('qarz', models.SmallIntegerField()),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.ombor')),
            ],
        ),
    ]
